runtime: nodejs20

env_variables:
  NODE_ENV: "production"

handlers:
- url: /_next/static
  static_dir: .next/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
