runtime: nodejs20

env_variables:
  NODE_ENV: "production"

# Security: Force HTTPS for all handlers
handlers:
- url: /_next/static
  static_dir: .next/static
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options: "DENY"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Security: Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  max_concurrent_requests: 80

# Security: VPC connector (optional, for private resources)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME

# Security: Use App Engine firewall rules
# Configure in GCP Console: App Engine > Settings > Firewall Rules

