steps:
  # Security: Dependency audit
  - name: 'node:20'
    entrypoint: npm
    args: ['audit', '--audit-level=high']
    id: 'security-audit'

  # Installer les dépendances
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: 'install-dependencies'
  
  # Security: Run linter
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'lint']
    id: 'lint'
    waitFor: ['install-dependencies']
  
  # Build de l'application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build'
    waitFor: ['install-dependencies', 'lint']
    env:
      - 'NODE_ENV=production'
  
  # Security: Scan for secrets in code
  - name: 'trufflesecurity/trufflehog:latest'
    args: ['filesystem', '.', '--only-verified', '--fail']
    id: 'secret-scan'
    waitFor: ['build']
    allowFailure: true

  # Security: Container vulnerability scan (if using containers)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/reussitess-nexus:$BUILD_ID', '.']
    id: 'docker-build'
    waitFor: ['build']
    allowFailure: true

  - name: 'aquasec/trivy'
    args: ['image', '--severity', 'HIGH,CRITICAL', 'gcr.io/$PROJECT_ID/reussitess-nexus:$BUILD_ID']
    id: 'trivy-scan'
    waitFor: ['docker-build']
    allowFailure: true
  
  # Déployer sur Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy'
    waitFor: ['build', 'secret-scan']

  # Post-deployment security verification
  - name: 'gcr.io/cloud-builders/curl'
    args: ['-I', 'https://$PROJECT_ID.appspot.com']
    id: 'verify-deployment'
    waitFor: ['deploy']

# Security: Enhanced timeout and machine type
timeout: '2400s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
  # Security: Use service account with minimal permissions
  # serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cloudbuild@$PROJECT_ID.iam.gserviceaccount.com'

# Security: Store build logs securely
logsBucket: 'gs://${PROJECT_ID}_cloudbuild_logs'

# Security: Substitution variables (use Secret Manager for sensitive data)
substitutions:
  _DEPLOY_REGION: 'us-central1'

# Available images for security scanning
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
    env: 'JWT_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/encryption-key/versions/latest
    env: 'ENCRYPTION_KEY'

