steps:
  # Installer les dépendances
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
  
  # Build de l'application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
  
  # Déployer sur Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'

options:
  machineType: 'N1_HIGHCPU_8'
