steps:
  # Installer les dépendances
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
  
  # Build de l'application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
  
  # Déployer sur Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'

# Bucket de logs pour Cloud Build (requis avec service_account)
# Remplacez avec votre bucket GCS, exemple: gs://votre-projet_cloudbuild
logsBucket: 'gs://YOUR_PROJECT_ID_cloudbuild'

options:
  machineType: 'N1_HIGHCPU_8'
  # Option de logging pour Cloud Build
  # Options: CLOUD_LOGGING_ONLY, GCS_ONLY, LEGACY, NONE
  logging: CLOUD_LOGGING_ONLY

# Compte de service (optionnel, décommentez et configurez si nécessaire)
# serviceAccount: 'projects/YOUR_PROJECT_ID/serviceAccounts/YOUR_SERVICE_ACCOUNT@YOUR_PROJECT_ID.iam.gserviceaccount.com'
