steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build Next.js
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'NEXT_TELEMETRY_DISABLED=1'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
